### ISSUE TITLE
[Feature]: マージ元･先の両ブランチの名前を取得する方法

### ISSUE THREAD

**Issue by NakashimaShuusaku** [ee090186/GitHubActionsTest#5]
# summary
`git log --graph  --pretty=oneline --all --abbrev-commit --boundary --left-right master...test`
コマンドを`GitHub Actions`で実行する際、`branchA...branchB`のbranch名を取得する必要があるため

<br>
<br>

# 方法
```yml
on:
  pull_request:
    types: [opened, closed]

jobs:
  debug:
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: Print branch name
        env:
          HEAD_BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
        run: |
          echo $HEAD_BRANCH_NAME
          echo $BASE_BRANCH_NAME
```

<br>
<br>

# Refelence
[GitHub Actionsでブランチ名を扱う方法](https://qiita.com/iery/items/43b72813c394050b8bbc)
[github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
