### ISSUE TITLE
[Bug]: 環境変数がうまく展開できない

### ISSUE THREAD

**Issue by ee090186** [ee090186/GitHubActionsTest#9]
### # What happened?

以下のようなワークフローファイルだと､`git log`のステップで環境変数が展開されなかった

```yml
- name: Print branch name
        env:
          HEAD_BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
        run: |
          echo $HEAD_BRANCH_NAME
          echo $BASE_BRANCH_NAME     
          "HEAD_BRANCH_NAME=$HEAD_BRANCH_NAME" >> $env:GITHUB_ENV
          "BASE_BRANCH_NAME=$BASE_BRANCH_NAME" >> $env:GITHUB_ENV
      - name: git setting
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" 
      - name: git log
        run: |
          git log --pretty=oneline --abbrev-commit --boundary --left-right "${{ env.HEAD_BRANCH_NAME }}...${{ env.BASE_BRANCH_NAME }}" >> pstest.txt
        shell: pwsh
```

<br>
<br>

### Relevant log output

環境変数設定ステップでは取得できているよう
```pwsh
Run echo $HEAD_BRANCH_NAME
  echo $HEAD_BRANCH_NAME
  echo $BASE_BRANCH_NAME     
  "HEAD_BRANCH_NAME=$HEAD_BRANCH_NAME" >> $env:GITHUB_ENV
  "BASE_BRANCH_NAME=$BASE_BRANCH_NAME" >> $env:GITHUB_ENV
  shell: C:\Program Files\PowerShell\[7](https://github.com/ee090186/GitHubActionsTest/actions/runs/4468492113/jobs/7849306771#step:3:7)\pwsh.EXE -command ". '{0}'"
  env:
    HEAD_BRANCH_NAME: test
    BASE_BRANCH_NAME: main
```

<br>

`git log ~ --left-right "master...test"`のようになって欲しいが､空になっている

```pwsh
Run git log --pretty=oneline --abbrev-commit --boundary --left-right "..." >> pstest.txt
  git log --pretty=oneline --abbrev-commit --boundary --left-right "..." >> pstest.txt
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    HEAD_BRANCH_NAME: 
    BASE_BRANCH_NAME: 
```
<br>
<br>

### Cause

`Print branch name`部分で`env:`と設定している部分が`"HEAD_BRANCH_NAME=$HEAD_BRANCH_NAME" >> $env:GITHUB_ENV`の処理と干渉している？

<br>
<br>

### Solution

`Print branch name`ステップの以下の部分を削除する
```yml
        env:
          HEAD_BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
```
<br>
<br>

#### 確認結果
(`"`をコマンド全体に使用していないため､`git log`コマンド自体はエラーだが､環境変数は`test...main`に展開されている)
```pwsh
Run git log --pretty=oneline --abbrev-commit --boundary --left-right "test...main" >> pstest.txt
  git log --pretty=oneline --abbrev-commit --boundary --left-right "test...main" >> pstest.txt
  shell: C:\Program Files\PowerShell\[7](https://github.com/ee090186/GitHubActionsTest/actions/runs/4468773703/jobs/7849959353#step:5:8)\pwsh.EXE -command ". '{0}'"
  env:
    HEAD_BRANCH_NAME: test
    BASE_BRANCH_NAME: main
fatal: ambiguous argument 'test...main': unknown revision or path not in the working tree.
```
